align_assignment    = true
align_conditional	= false
align_matrix	    = true
align_pair_arrow	= true
align_struct_field	= true
always_for_in	    = "nothing" 
always_use_return   = false
annotate_untyped_fields_with_any = false
conditional_to_if   = false
disallow_single_arg_nesting = false
enforce_triplequoted_docstrings = true
for_in_replacement  = "in"
force_long_function_def = false
format_docstrings = true
import_to_using = false
indent = 4
indent_submodule = false
join_lines_based_on_source = false
long_to_short_function_def = true
margin = 92
max_iterations = 1
normalize_line_endings = "unix"
pipe_to_function_call = false
remove_extra_newlines = true
sciml_margin_overrun = 20
separate_kwargs_with_semicolon = false
short_circuit_to_if = false
short_to_long_function_def = true
surround_whereop_typeparameters = false
trailing_comma = true
trailing_zero = true
transform_syntax_in_macros = false
v2_stable_multiline_strings = false
variable_call_indent = []
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = false
yas_style_nesting = false